### ISSUE TITLE
Override variables

### ISSUE THREAD

**Issue by octant** [mkhairi/materialize-sass#26]
Is there any way to override the variables? Attempting to set them before the import of materialize causes errors and defining them after has no effect.

**Comment by xamenrax** [comment]
@octant try this in `application.scss` file:
```
$h1-fontsize: 18rem !default;

@import "materialize";
```

**Comment by octant** [comment]
Well that works. I was trying to set the $primary-color variable using [the example](http://materializecss.com/sass.html) they show on the materialize site. I placed it before the import of materialize like so:

    $primary-color: color("blue", "lighten-2") !default;
    
    @import "materialize";

I get an error stating that "$color: 'color("blue", "lighten-2")' is not a color for `lighten'"

**Comment by xamenrax** [comment]
@octant all colours stored in `_color.scss` and it's imported with `@import "materialize"`

**Comment by mkhairi** [comment]
hi @octant,  @import "materialize/components/color";  first should do the trick. :)

**Comment by emerak** [comment]
I have this in my application.scss file and iit's not working

@import "materialize";
$primary-color: color("teal", "darken-4") !default;

it simply does not change anything, what i am doing wrong?

**Comment by mkhairi** [comment]
hi @emerak, see #28 or #31

**Comment by gerep** [comment]
I still doesn't work here.

This is my application.scss

```scss
@import 'materialize/components/color';
$primary-color: color("teal", "darken-4") !default;
@import 'materialize';
@import url('//fonts.googleapis.com/css?family=Open+Sans:400italic,800,400');
@import 'font-awesome-sprockets';
@import 'font-awesome';

* {
  font-family: 'Open Sans', sans-serif;
}
```
